Accelerate_31327/Controllers/TechnologyController.cs
using Accelerate_31327.Models;
using Accelerate_31327.Repository;
using Accelerate_31327.Security;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Accelerate_31327.Controllers
{
    public class TechnologyController : Controller
    {
        ITechnology objTechnology = new Technology();


        [OnAuthorize(Roles = "Administrator,Guest")]
        public ActionResult Index()
        {
            var empList = objTechnology.GetTechnologyList();
            return View(empList);
        }

        //
        // GET: /Technology/Details/5
        [OnAuthorize(Roles = "Administrator")]
        public ActionResult AddEditTechnology(int id = 0)
        {
            var objTechnologyModel = new TechnologyModel();
            if (id > 0)
            {
                objTechnologyModel = objTechnology.GetTechnologyDetailsByID(id);
            }
            return PartialView(objTechnologyModel);
        }

        [OnAuthorize(Roles = "Administrator")]
        public ActionResult TechnologyDetail(int id = 0)
        {
            var objTechnologyModel = new TechnologyModel();
            if (id > 0)
            {
                objTechnologyModel = objTechnology.GetTechnologyDetailsByID(id);
            }
            ViewBag.TechnologyDetail = true;
            return PartialView("AddEditTechnology", objTechnologyModel);
        }

        [OnAuthorize(Roles = "Administrator")]
        public ActionResult TechnologyDelete(int id = 0)
        {
            var objTechnologyModel = new TechnologyModel();
            if (id > 0)
            {
                objTechnologyModel = objTechnology.GetTechnologyDetailsByID(id);
            }
            ViewBag.TechnologyDelete = true;
            return PartialView("AddEditTechnology", objTechnologyModel);
        }

        [HttpPost]
        [OnAuthorize(Roles = "Administrator")]
        public ActionResult AddEditDetail(TechnologyModel objTechnologyModel)
        {
            objTechnologyModel.CreatedBy = objTechnologyModel.UpdatedBy = User.Identity.Name;
            var IsSaved = objTechnology.AddTechnologyDetails(objTechnologyModel);
            return RedirectToAction("Index");
        }
  
         //
        // GET: /Technology/Delete/5
         [OnAuthorize(Roles = "Administrator")]
        public ActionResult DeleteTechnology(int id)
        {
            var IsDelete = false;
            if (id > 0)
            {
                IsDelete = objTechnology.DeleteTechnologyByID(id);
            }
            return RedirectToAction("Index");
        }

       
    }
}

Accelerate_31327/Views/Technology/AddEditTechnology.cshtml
@model Accelerate_31327.Models.TechnologyModel

@{
    var showDetails = Convert.ToBoolean(ViewBag.TechnologyDetail);
    var showDeleteMessage = Convert.ToBoolean(ViewBag.TechnologyDelete);
}
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    

    @if (showDeleteMessage)
    {
       <h3 id="myModalLabel">Delete Technology</h3>
    }
    else if (showDetails)
    {
      <h3 id="myModalLabel">Technology detail</h3>
    }
    else
    {
        <h3 id="myModalLabel">Add Technology</h3>
    }

</div>
@using (Ajax.BeginForm("AddEditDetail", "Technology", new AjaxOptions
{
    HttpMethod = "POST",
    InsertionMode = InsertionMode.InsertAfter,
    OnSuccess = "updateAddressSuccess()",
    OnFailure = "dialogFailure()",
    OnBegin = "dialogBegin()",
    OnComplete = "dialogComplete()",
    UpdateTargetId = "employeeDetails"
}))
{
    @Html.ValidationSummary()
  
    <div class="modal-body" style="width:160%">
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @if (showDeleteMessage)
            {
                <span>Are you sure you want to delete this?</span>
            }else{
                
            
            @Html.ValidationSummary(true)
            if (Model != null && Model.Technology_ID != 0)
            {
                <div class="form-group">
                    @Html.LabelFor(model => model.Technology_ID, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @if (showDetails)
                        {
                            @Html.DisplayFor(model => model.Technology_ID, new { @class = "control-label col-md-2", @readonly = true })
                        }
                        else
                        {
                            @Html.TextBoxFor(model => model.Technology_ID, new { @class = "", @readonly = true })
                            @Html.ValidationMessageFor(model => model.Technology_ID)
                        }

                    </div>
                </div>
            }
            <div class="form-group">
                @Html.LabelFor(model => model.Technology_Name, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @if (showDetails)
                    {
                        @Html.DisplayFor(model => model.Technology_Name)
                    }
                    else
                    {
                        @Html.EditorFor(model => model.Technology_Name)
                        @Html.ValidationMessageFor(model => model.Technology_Name)
                    }
                </div>
            </div>
            }
        </div>
    </div>

    <div class="modal-footer">
@if (showDeleteMessage)
{ 
      @Html.ActionLink("OK", "DeleteTechnology", new { id = Model.Technology_ID }, new { @class = "btn btn-primary" })
        <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
}
else if (showDetails)
{
    <button class="btn btn-primary" data-dismiss="modal" aria-hidden="true">OK</button>
}
else
{
    <button class="btn btn-primary" type="submit">Save</button>
        <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button> 
}
       

    </div>

}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.js"></script>

Accelerate_31327/Views/Technology/Index.cshtml
@model  List<Accelerate_31327.Models.TechnologyModel>

@using GridMvc.Html
@{
    ViewBag.Title = "Technology Details";
}
@*@{
        Layout = null;
    }*@

<h2>Technology Details</h2>
<link href="@Url.Content("~/Content/Gridmvc.css")" rel="stylesheet" />
<link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" />
<script src="@Url.Content("~/Scripts/jquery-1.10.2.min.js")"></script>
<script src="@Url.Content("~/Scripts/gridmvc.min.js")"></script>

@Html.ActionLink("Add Technology ", "AddEditTechnology", "Technology",
                null, new { @id = "btnCreate", @class = "btn-bootstrap-dialog btn btn-primary navbar-text navbar-right" })
<div class="code-cut" id="employeeDetails">

    @Html.Grid(Model).Columns(columns =>
                    {
                        columns.Add(c => c.Technology_ID).Titled("Technology ID").Filterable(true);
                        columns.Add(c => c.Technology_Name).Titled("Technology Name").Filterable(true);
                             columns.Add()
                        .Encoded(false)
                        .Sanitized(false)
                        .RenderValueAs(o => Html.ActionLink("Edit", "AddEditTechnology", new { id = o.Technology_ID }, new { @class = "edit" }).ToString() + " | " +
                                            Html.ActionLink("Details", "TechnologyDetail", new { id = o.Technology_ID }, new { @class = "detail" }).ToString() + " | " +
                                            Html.ActionLink("Delete", "TechnologyDelete", new { id = o.Technology_ID }, new { @class = "delete" }));


                    }).WithPaging(10).Sortable(true).Named("EMP")
</div>

<script type="text/javascript">

    $(function () {

        //Optional: turn the chache off
        $.ajaxSetup({ cache: false });

        $('#btnCreate').click(function () {
            $('#dialogContent').load(this.href, function () {
                $('#dialogDiv').modal({
                    backdrop: 'static',
                    keyboard: true
                }, 'show');
                // bindForm(this);
            });
            return false;
        });

        $('.edit').click(function () {
            $('#dialogContent').load(this.href, function () {
                $('#dialogDiv').modal({
                    backdrop: 'static',
                    keyboard: true
                }, 'show');
                // bindForm(this);
            });
            return false;
        });

        $('.detail').click(function () {
            $('#dialogContent').load(this.href, function () {
                $('#dialogDiv').modal({
                    backdrop: 'static',
                    keyboard: true
                }, 'show');
                // bindForm(this);
            });
            return false;
        });

        $('.delete').click(function () {
            $('#dialogContent').load(this.href, function () {
                $('#dialogDiv').modal({
                    backdrop: 'static',
                    keyboard: true
                }, 'show');
                // bindForm(this);
            });
            return false;
        });
    });

    function bindForm(dialog) {
        $('form', dialog).submit(function () {
            $.ajax({
                url: this.action,
                type: this.method,
                data: $(this).serialize(),
                success: function (result) {
                    if (result.success) {
                        $('#dialogDiv').modal('hide');
                        // Refresh:
                        // location.reload();
                    } else {
                        $('#dialogContent').html(result);
                        bindForm();
                    }
                }
            });
            return false;
        });
    }

</script>



<!-- modal placeholder-->
<div id='dialogDiv' class='modal fade' tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='dialogContent'></div>
        </div>
    </div>
</div>